### ISSUE TITLE
Typing "[" or functions causes webpage to crash

### ISSUE THREAD

**Issue by kungpaogao** [cornell-dti/course-reviews-react-2.0#230]
## Problem
Typing characters that mean something in JavaScript will cause the webpage to crash.

Examples:
- (
- )
- [
- console.log(
- return (

## Cause
I think the query is not getting sanitized properly for the endpoint `getClassesByQuery`. The other endpoints seem to respond normally with an empty list, so I think it's the `guard` whitelist that's causing issues. 

https://github.com/cornell-dti/course-reviews-react-2.0/blob/db014b2a1b03468b236befb959a04174c90b6806/server/endpoints/Search.ts#L135-L155

Might be worth looking into `escape` methods provided by `express-validator`.

## Other
OS: macOS 10.15.7
Browser: Firefox Developer Edition 85.0b8

**Comment by khemritolya** [comment]
Should be fixed. Thanks for the report @kungpaogao !
