### ISSUE TITLE
Can't directly navigate to page

### ISSUE THREAD

**Issue by kungpaogao** [cornell-dti/course-reviews-react-2.0#266]
## Overview
Can't navigate directly to a course review page when there is no last search. 

## Steps to reproduce
1. clear local storage 
2. type in or paste in link to course page (e.g., `https://www.cureviews.org/course/CS/4110`)
3. nothing shows up

## Cause
- website attempts to find `last-search` in local storage to show back button on mobile
- render issues when this isn't present (i.e., first time users getting a direct link)
https://github.com/cornell-dti/course-reviews-react-2.0/blob/cc767073a89532b67faf1979e5cf2cf4d67a408a/client/src/ui/ResultsDisplayMobile.tsx#L54

## Screenshots
Firefox
![image](https://user-images.githubusercontent.com/11168401/117591437-7c655a00-b102-11eb-867b-6df346e96eda.png)

## Device info
- macOS 10.15.7
- tested on both Firefox Developer Edition 89.0b6 and Chrome 90.0.4430.93

**Comment by khemritolya** [comment]
Should be fixed. Thanks for the report @kungpaogao !
