### ISSUE TITLE
404 for Undefined url route.

### ISSUE THREAD

**Issue by AkashAryal** [cornell-dti/course-reviews-react-2.0#286]
Currently when you type in a random url like "cureviews.org/diwf" we get to this page:

![image](https://user-images.githubusercontent.com/31822474/138000535-0f839518-2918-40a7-8930-0d5ec0acc6a9.png)

I think it would be good if we had a dedicated 404 page.

**Low Priority**
This is not something super important

**Comment by michelleli01** [comment]
solved in #310

**Comment by michelleli01** [comment]
fixed in #310
