### ISSUE TITLE
Remove unused components

### ISSUE THREAD

**Issue by kungpaogao** [cornell-dti/course-reviews-react-2.0#328]
Following rewrites for `ClassView` (#287, #294, #302), we need to remove dead code and move stuff around:

- ResultsDisplayMobile
- ClassView
- move @AnkitLakkapragada's code on `Form` to `ReviewForm` 

There might be other bugs, so we'll have to check for those too.

**Comment by michelleli01** [comment]
There are a lot of unused components lingering around in the codebase. Will formalize in another issue.
