### ISSUE TITLE
Popup auth css is a bit messed up

### ISSUE THREAD

**Issue by AkashAryal** [cornell-dti/course-reviews-react-2.0#334]

**Comment by kungpaogao** [comment]
Do you have a screenshot? Also, this should be addressed by some changes in #302.

**Comment by AkashAryal** [comment]
Ah yea I just created this as a note since it was mentioned apparently during the tabling today. I havent looked too deeply

**Comment by michelleli01** [comment]
should be fixed from recent PRs
