### ISSUE TITLE
Wrong course on exact search

### ISSUE THREAD

**Issue by Coreball** [cornell-dti/course-reviews-react-2.0#360]
Sometimes the wrong course will appear after putting in an exact match, like "CS 4414" will show the page for "CS 4420" instead. This happens somewhat rarely, but in a few minutes of trying I managed to reproduce it at least twice, as shown in these video clips. It seems that sometimes the first item of the autocomplete doesn't match the input and that first item is used for the next page.

https://user-images.githubusercontent.com/22627336/188242300-ab94f100-b96d-45d3-aab5-332818f1d305.mov

https://user-images.githubusercontent.com/22627336/188242301-b66b665a-5862-4a37-a67a-bd86920d5433.mov

**Comment by kungpaogao** [comment]
I think this was somewhat addressed in #326, but that hasn't been deployed yet 😢

**Comment by michelleli01** [comment]
This should be somewhat fixed as Andrew said above in #326. Further improvements will be made in the future in terms of search functionality.
