### ISSUE TITLE
Navigation Bar on Mobile View

### ISSUE THREAD

**Issue by michelleli01** [cornell-dti/course-reviews-react-2.0#390]
The navigation bar on the mobile view gets distorted. 
![image](https://github.com/cornell-dti/course-reviews-react-2.0/assets/11303631/e3441574-218d-4f99-a39d-cea96dcbfc25)

When user is not signed in, the sign in button hides behind navigation bar.

**Comment by adithyaakrishna** [comment]
Hi @michelleli01 
Could you please let me know if we are allowed to work on this? if so, I have a fix ready for this one :)

**Comment by michelleli01** [comment]
Hi @adithyaakrishna we would prefer for our developers on Cornell DTI to work on these issues! Thank you for your interest though!

**Comment by adithyaakrishna** [comment]
No problem :)
Thanks for letting me know! I really appreciate it!

**Comment by michelleli01** [comment]
Addressed in PR
