### ISSUE TITLE
Classes with no professor won't let a review be submitted

### ISSUE THREAD

**Issue by SheaBelsky** [cornell-dti/course-reviews-react-2.0#44]
http://www.cureviews.org/course/EDUC/2610

This class, for whatever reason, has no professor(s) assigned to it. However, trying to submit a review will still prompt for one. Is this an issue with gaps in server-side data (where there should always be a professor), a situation where the client should know there is no professor to check, or both?

**Comment by khemritolya** [comment]
As of SP 21, this seems to be fixed. We really need to run the scraper more regularly.
