### ISSUE TITLE
What license is this repo under?

### ISSUE THREAD

**Issue by SheaBelsky** [cornell-dti/course-reviews-react-2.0#45]
It's open source so I want to say MIT/ISC. But this repo, and the `package.json` file, should reflect a license to make forking/cloning clearer. This file should also contain information standard to a `package.json` file like a name, description, and primary author (put down Cornell DTI for this field.)

Also, why is this `private: true`? This is not a private repository.

**Comment by khemritolya** [comment]
See #196
