### ISSUE TITLE
Autofill Dropdown Appears When Searching

### ISSUE THREAD

**Issue by rockon999** [cornell-dti/course-reviews-react-2.0#55]
In Chrome (v71) whenever the search box is selected, Chrome attempts to provide previous entries/autofill data. This is rather unhelpful and looks odd as several data points aren't actually from the search dropdown and the dropdown spans only the left-edge of the box.

Example:
![cureviews-dropdown](https://user-images.githubusercontent.com/2943271/51956665-858cfa00-2416-11e9-98da-2c409034b601.png)

**Comment by SamChou19815** [comment]
Looks like it's fixed now.
